# Generated by Django 2.0.6 on 2018-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
